### ISSUE TITLE
Event Listener Registration required?

### ISSUE THREAD

**Issue by Wulfheart** [nwilging/laravel-discord-bot#11]
Hey,

currently it is not working for me locally. I debugged it using XDebug and found out that no listener has been found even though a listener has been created in the App\Listener namespace.
Do I need to register the events manually or do any other steps?

**Comment by nwilging** [comment]
yes, it must be registered in the event service provider. The way that the package dispatches those events is by checking for registered evens on the app event dispatcher -- this requires that the listeners are registered.

In the `EventServiceProvider`, you'd do this:
```
use Nwilging\LaravelDiscordBot\Events\MessageComponentInteractionEvent;

class EventServiceProvider extends ServiceProvider
{
   protected $listen = [
      MessageComponentInteractionEvent::class => [
         MyListener::class,
      ],
   ];
}
```

Keep in mind that when using listeners to manipulate default loading behavior, the _first listener_ is used (see [Extending the message component interaction handler](https://github.com/nwilging/laravel-discord-bot#extending-the-message-component-interaction-handler))

This is a bit confusing, so I will add more information around this to the readme.

**Comment by Wulfheart** [comment]
Ah. Unfortunately I didn't find it in the docs. Thanks for the clarification.
