### ISSUE TITLE
FieldEmbed on EmbedBuilder

### ISSUE THREAD

**Issue by Dennion** [nwilging/laravel-discord-bot#13]
Heyho,

how works the FieldEmbed in the EmbedBuilder? I wantcreate a Embed with title, description, url and 5 fields.
My Code:
`$embedBuilder = new EmbedBuilder(); 
$geneticEmbed = new GenericEmbed('⚠️ Report ⚠️', 'Report'); 
$embedBuilder->addEmbed($geneticEmbed); 
$field1 = new FieldEmbed('Comment', 
$this->comment, 'Comment'); 
$embedBuilder->addEmbed($field1); 
$embedBuilder->addEmbed(new FieldEmbed('message', $this->message, 'Message')); Log::debug($embedBuilder->getEmbeds());`

but the Result:
[2023-04-18 20:17:52] local.DEBUG: array ( 0 =>  \Nwilging\LaravelDiscordBot\Support\Embeds\GenericEmbed::__set_state(array( 'title' => '⚠️ Report ⚠️', 'description' => 'Report', 'timestamp' => NULL, 'color' => NULL, )), 1 =>  \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed::__set_state(array( 'title' => 'Comment', 'description' => NULL, 'timestamp' => NULL, 'color' => NULL, 'name' => 'Comment', 'value' => 'asdasdasd', 'inline' => NULL, )), 2 =>  \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed::__set_state(array( 'title' => 'Message', 'description' => NULL, 'timestamp' => NULL, 'color' => NULL, 'name' => 'message', 'value' => 'Ein Beitrag wurde gemeldet', 'inline' => NULL, )), 

In Discord its show:
https://prnt.sc/Vfb_rktsi0GO

I want to have:
https://prnt.sc/RGySrrIZiYGA

who it works?

Greets,
Dennion

**Comment by nwilging** [comment]
this is an issue with the `GenericEmbed`, as it should support adding additional fields/embeds within it.

I will fix this in the next version, within the next 24 hours. At which point the valid syntax would be:
```
$builder = new \Nwilging\LaravelDiscordBot\Support\Builder\EmbedBuilder();

$genericEmbed = new \Nwilging\LaravelDiscordBot\Support\Embeds\GenericEmbed();

$field1 = new \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed('test', 'test');
$field2 = new \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed('test', 'test');

$field1->inline();
$field2->inline();

$genericEmbed->addField($field1)
    ->addField($field2);

$builder->addEmbed($genericEmbed);
```

**Comment by Dennion** [comment]
Ah ok... that's what I thought

Thanks very much

**Comment by nwilging** [comment]
You can use this in version `1.1.0`!

**Comment by Dennion** [comment]
Heyho,

now i become 
`Client error: `POST https://discord.com/api/channels/******/messages` resulted in a `400 Bad Request` response:{"embeds": ["0"]}`

**Comment by nwilging** [comment]
Can you post the code used to create the embeds?

**Comment by Dennion** [comment]
I use for test your code

`$builder = new \Nwilging\LaravelDiscordBot\Support\Builder\EmbedBuilder();

        $genericEmbed = new \Nwilging\LaravelDiscordBot\Support\Embeds\GenericEmbed('⚠️ Report ⚠️', 'Report');

        $field1 = new \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed('test', 'test');
        $field2 = new \Nwilging\LaravelDiscordBot\Support\Embeds\FieldEmbed('test', 'test');

        $field1->inline();
        $field2->inline();

        $genericEmbed->addField($field1)
            ->addField($field2);

        $builder->addEmbed($genericEmbed);
        return [
            'contentType' => 'rich',
            'channelId' => '****',
            'embeds' => $builder->getEmbeds(),
        ];`

**Comment by nwilging** [comment]
oops, mistake on my end. Try version `1.1.1`. Same code as you have above should work

**Comment by Dennion** [comment]
i works fine :)

thank you
