### ISSUE TITLE
Post image with content

### ISSUE THREAD

**Issue by sanskar-mk2** [nwilging/laravel-discord-bot#15]
How to post plain text and image together with library.

Any example would be appreciated.

**Comment by nwilging** [comment]
is the image a file or a link? discord auto-embeds image URLs, so you could send a plaintext message with the image url and your text.

If the image is a file/attachment you'll wanna use rich text messages with the embed builder.
```
$builder = new \Nwilging\LaravelDiscordBot\Support\Builder\EmbedBuilder();
$image = new \Nwilging\LaravelDiscordBot\Support\Embeds\ImageEmbed('url', 'title', 'description');
$builder->addEmbed($image);
```
(note that an image URL is still used here, but in this case discord will treat that as an attachment)

**Comment by sanskar-mk2** [comment]
So no native attachments possible? Only links? Will this be added? Many wrappers have the ability to upload images directly.

**Comment by nwilging** [comment]
Yes, I've been working on a v2 that essentially contains wrappers for the entire discord API. V1 was mostly centered around notification channels, but was expanded to do interaction handling.

**Comment by sanskar-mk2** [comment]
Good luck, thanks.
