### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by blue-bear-tech** [nwilging/laravel-discord-bot#3]
Was looking in the source code but couldn't find a way to use it. Can you update the readme file please and include a basic send message?

**Comment by nwilging** [comment]
The readme includes a basic example of plaintext and rich text in a Laravel notification: https://github.com/nwilging/laravel-discord-bot#notification-channel-usage

The readme of this package doesn't cover implementing laravel notifications as a whole as that's outside the scope of the package - it assumes you already know how to use laravel notifications in abstract. https://laravel.com/docs/9.x/notifications#sending-notifications

**Comment by blue-bear-tech** [comment]
Sorry, just started learning Laravel for a month now. I figured it out eventually in an hour by going through the Laravel documentation.
