### ISSUE TITLE
[Help] Does it have a solution to handle command messages?

### ISSUE THREAD

**Issue by romulosalmeida** [nwilging/laravel-discord-bot#4]
Hey,
Thank you for sharing your library publicly.
I'm really excited to use it in my bot project which deal with user command messages.

Does it have a built-in solution to handle it?

I saw this part of the code:

![image](https://user-images.githubusercontent.com/37348255/214999691-52fd1ce9-2439-43f8-a728-d2e23f5dca86.png)

But I suppose it is not coded yet, am I correct?

Thank you in advance.

**Comment by nwilging** [comment]
Correct there is currently no way to extend the app command handler

This wouldn't be too much work to add dispatching/extension capabilities like exist in the message interaction handler. I'll look into it later this week

**Comment by nwilging** [comment]
There is a dev branch available if you'd like to pull it in: `application-command-support` (with composer: `nwilging/laravel-discord-bot:dev-application-command-support`

If you just need the ability to intercept app command events, this branch will work fine. It's still in progress as I need to finish writing tests for the command helper classes. They can be used to create commands via the API if needed but currently have no test coverage on that branch.

**Comment by romulosalmeida** [comment]
Thank you very much!
I’ll check it out.

Great week ahead.

**Comment by nwilging** [comment]
This is fully supported in [1.0.0](https://github.com/nwilging/laravel-discord-bot/releases/tag/1.0.0). See [readme](https://github.com/nwilging/laravel-discord-bot/tree/1.0.0#application-commands) for additional information
