### ISSUE TITLE
The RichText Embed is Missing The Message field

### ISSUE THREAD

**Issue by salman-ibrahim** [nwilging/laravel-discord-bot#6]
I am unable to find a way to add message to embed. All I can do is add title, footer, thumb etc but there is not way I could add message. Am I missing something here?

**Comment by nwilging** [comment]
based on the docs linked below, I don't see that a `message` field is supported. Is there other documentation to suggest otherwise?

https://discord.com/developers/docs/resources/channel#embed-object-embed-structure

**Comment by salman-ibrahim** [comment]
The Description or Content I would call it. As you can see it in the screenshot attached. The text under "Old User" [Screenshot](https://imgur.com/a/8SIXLDb)

I am sorry about my bad understanding of Discord docs but it has to be **Description**.

**Comment by nwilging** [comment]
The `GenericEmbed` object already accepts the `description` parameter, so I believe you can accomplish what you're looking for with:
```
$msg = new \Nwilging\LaravelDiscordBot\Support\Embeds\GenericEmbed('test title', 'test description');
```

![image](https://user-images.githubusercontent.com/44447928/220644162-21ea389e-19ea-432c-a14a-678b623038fd.png)

**Comment by salman-ibrahim** [comment]
Hey thank you so much for that. I really appreciate that.
