### ISSUE TITLE
[HELP] How to regster Commands

### ISSUE THREAD

**Issue by mrwhy-orig** [nwilging/laravel-discord-bot#7]
Hi, maybe I over read it, but I don't understand how to register the Bot commands with discord. Does this package take care of it? Maybe like db migrations? Or do I have to take care of it on my own? Do you have a full example for it? Thanks!

**Comment by nwilging** [comment]
There are a few examples in the readme under [Application Commands](https://github.com/nwilging/laravel-discord-bot#application-commands)

The examples include creating, updating, and deleting, as well as examples of how to use options/etc with your commands.

As far as creating them with the same pattern as DB migrations, that's not something this package supports by default.

Running a Create operation with the same command name will result in an update to the existing command. So you could create/update them in seeders possibly.

**Comment by mrwhy-orig** [comment]
Yepp, I saw those, but didn't get where to implement them... but now it makes sense. Thanks!
